### ISSUE TITLE
fire initial fails because of missing MetadataProperties

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#2112]
```
Local
Exception
: 
Error: java.lang.IllegalStateException: Required properties "date-parse-pattern", "date-time-parse-pattern", "number-parse-pattern", "time-parse-pattern" missing. at IllegalStateException_2_g$.createError_0_g$ [as createError_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3442:10) at IllegalStateException_2_g$.initializeBackingError_0_g$ [as initializeBackingError_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3505:48) at IllegalStateException_2_g$.Throwable_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3348:8) at IllegalStateException_2_g$.Exception_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3617:18) at IllegalStateException_2_g$.RuntimeException_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3664:18) at new IllegalStateException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:12872:25) at SpreadsheetMetadataComponents_1_g$.reportIfMissing_0_g$ [as reportIfMissing_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1477095:21) at SpreadsheetMetadataEmpty_1_g$.createParser_3_g$ [as createParser_6_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1476508:19) at SpreadsheetMetadataEmpty_1_g$.parser_5_g$ [as parser_21_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1477351:15) at SpreadsheetViewportFormulaComponentSpreadsheetFormulaComponentParserFunction_1_g$.apply_33153_g$ [as apply_34239_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1451366:56) at SpreadsheetViewportFormulaComponentSpreadsheetFormulaComponentParserFunction_1_g$.apply_33152_g$ [as apply_34216_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1451346:15) at SpreadsheetFormulaComponentValidator_1_g$.isValid_11_g$ [as isValid_26_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1437684:49) at SpreadsheetFormulaComponentValidator_1_g$.isValid_10_g$ [as isValid_24_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1437678:15) at SpreadsheetTextBoxValidator_1_g$.isValid_23_g$ [as isValid_30_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1447228:30) at SpreadsheetTextBoxValidator_1_g$.isValid_22_g$ [as isValid_24_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1447224:15) at TextBox_1_g$.doValidate_0_g$ [as doValidate_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:97866:34) at TextBox_1_g$.validate_6_g$ [as validate_35_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:98174:17) at TextBox_1_g$.validate_5_g$ [as validate_34_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:97784:15) at $validate_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:103536:27) at TextBox_1_g$.validate_4_g$ [as validate_33_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:97780:10) at TextBox_1_g$.autoValidate_2_g$ [as autoValidate_8_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:97848:10) at TextBox_1_g$.withValue_3_g$ [as withValue_17_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:98609:8) at TextBox_1_g$.withValue_1_g$ [as withValue_16_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:98597:15) at TextBox_1_g$.setValue_13_g$ [as setValue_102_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:98568:8) at SpreadsheetTextBox_1_g$.setValue_82_g$ [as setValue_139_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1447015:21) at ParserSpreadsheetTextBox_1_g$.setStringValue_3_g$ [as setStringValue_9_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1441701:21) at SpreadsheetFormulaComponent_1_g$.setStringValue_2_g$ [as setStringValue_8_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1437626:21) at SpreadsheetViewportFormulaComponent_1_g$.refresh_30_g$ [as refresh_31_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1451127:18) at $onHistoryTokenChange_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1434539:26) at SpreadsheetViewportFormulaComponent_1_g$.onHistoryTokenChange_22_g$ [as onHistoryTokenChange_24_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1451050:3) at HistoryTokenWatchersEvent_1_g$.accept_511_g$ [as accept_1119_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1427708:18) at lambda$0_310_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1427596:12) at HistoryTokenWatchers$lambda$0$Type_1_g$.accept_508_g$ [as accept_1094_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1427642:3) at Watchers_1_g$.accept_1088_g$ [as accept_1094_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1544692:18) at HistoryTokenWatchers_1_g$.onHistoryTokenChange_2_g$ [as onHistoryTokenChange_24_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1427619:22) at App_1_g$.onHistoryTokenChange_0_g$ [as onHistoryTokenChange_23_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1424158:33) at App_1_g$.fireInitialHistoryToken_0_g$ [as fireInitialHistoryToken_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1424083:8) at App_1_g$.onModuleLoad_3_g$ [as onModuleLoad_4_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1424180:8) at Array.init_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:8444:33) at initializeModules_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:52:30) at apply_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:4428:28) at entry0_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:4498:14) at walkingkooka.spreadsheet.dominokit.App-0.js:4464:14 at gwtOnLoad_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:65:40) at walkingkooka.spreadsheet.dominokit.App-0.js:1544817:1
this
: 
SpreadsheetMetadataComponents_1_g$
missing_0_g$
: 
TreeSet_1_g$ {map_33_g$: TreeMap_1_g$}
Window
Global
```

```
```
<img width="624" alt="image" src="https://github.com/mP1/walkingkooka-spreadsheet-dominokit/assets/726970/42626d27-589b-45b5-91e0-e34e43ed26f0">

**Comment by mP1** [comment]
Cant repro
