### ISSUE TITLE
FetcherWatcher.onNoResponse(AppContext)

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#2354]
- this will be called for 204 no content response

**Comment by mP1** [comment]
Necessary to support the response after a DELETE spreadsheetMetadata

```
walkingkooka.spreads…nokit.App-0.js:3442 Uncaught (in promise) Error: java.lang.IllegalArgumentException: Unexpected content type null
    at IllegalArgumentException_2_g$.createError_0_g$ [as createError_3_g$] (walkingkooka.spreads…it.App-0.js:3442:10)
    at IllegalArgumentException_2_g$.initializeBackingError_0_g$ [as initializeBackingError_1_g$] (walkingkooka.spreads…it.App-0.js:3505:48)
    at IllegalArgumentException_2_g$.Throwable_3_g$ (walkingkooka.spreads…kit.App-0.js:3348:8)
    at IllegalArgumentException_2_g$.Exception_3_g$ (walkingkooka.spreads…it.App-0.js:3617:18)
    at IllegalArgumentException_2_g$.RuntimeException_3_g$ (walkingkooka.spreads…it.App-0.js:3664:18)
    at new IllegalArgumentException_2_g$ (walkingkooka.spreads…t.App-0.js:12837:25)
    at SpreadsheetMetadataFetcher_1_g$.onSuccess_18_g$ [as onSuccess_19_g$] (walkingkooka.spreads…App-0.js:1436123:29)
    at $lambda$1_9_g$ (walkingkooka.spreads…App-0.js:1434927:24)
    at Function.onInvoke_44_g$ (walkingkooka.spreads…App-0.js:1435015:10)
    at lambda_0_g$ (walkingkooka.spreads…kit.App-0.js:131:27)
```
