### ISSUE TITLE
context menu is broken for cell selection using label 

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#2565]
```
Uncaught Error: java.lang.UnsupportedOperationException
    at UnsupportedOperationException_1_g$.createError_0_g$ [as createError_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3442:10)
    at UnsupportedOperationException_1_g$.initializeBackingError_0_g$ [as initializeBackingError_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3505:48)
    at UnsupportedOperationException_1_g$.Throwable_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3330:8)
    at UnsupportedOperationException_1_g$.Exception_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3605:18)
    at UnsupportedOperationException_1_g$.RuntimeException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3652:18)
    at new UnsupportedOperationException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:14772:25)
    at SpreadsheetLabelName_1_g$.testColumn0_4_g$ [as testColumn0_7_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1503612:19)
    at SpreadsheetLabelName_1_g$.testColumn_0_g$ [as testColumn_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1500082:15)
    at SpreadsheetSelectionTestSpreadsheetSelectionVisitor_1_g$.visit_567_g$ [as visit_734_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1505356:42)
    at SpreadsheetColumnReference_1_g$.accept_813_g$ [as accept_1174_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1502888:16)
    at SpreadsheetSelectionTestSpreadsheetSelectionVisitor_1_g$.accept_511_g$ [as accept_1135_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1423570:20)
    at test_349_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1505330:16)
    at SpreadsheetLabelName_1_g$.test_344_g$ [as test_446_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1500070:10)
    at SpreadsheetCellSelectHistoryToken_1_g$.setMenu0_0_g$ [as setMenu0_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1430270:43)
```

label needs to be resolved and the actual cell-reference used 

```
    at SpreadsheetLabelName_1_g$.test_344_g$ [as test_446_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1500070:10)
    at SpreadsheetCellSelectHistoryToken_1_g$.setMenu0_0_g$ [as setMenu0_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1430270:43)
```

**Comment by mP1** [comment]
HistoryToken.setMenu0

```
         // right mouse happened over already selected selection...
                if (anchored.selection().test(selection)) { <------------------------ need to resolve label here...
                    menu = this.cast(SpreadsheetAnchoredSelectionHistoryToken.class)
                            .setMenu1();
                }
```
