### ISSUE TITLE
rows context menu then sort is broken. 

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#3217]
```
Error: walkingkooka.spreadsheet.parser.SpreadsheetParserException: Invalid column value 65823788 expected between 0 and 16384
    at SpreadsheetParserException_2_g$.createError_0_g$ [as createError_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3442:10)
    at SpreadsheetParserException_2_g$.initializeBackingError_0_g$ [as initializeBackingError_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3505:48)
    at SpreadsheetParserException_2_g$.Throwable_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3348:8)
    at SpreadsheetParserException_2_g$.Exception_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3617:18)
    at SpreadsheetParserException_2_g$.RuntimeException_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3664:18)
    at SpreadsheetParserException_2_g$.SystemException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1381562:25)
    at SpreadsheetParserException_2_g$.TextException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1477882:24)
    at SpreadsheetParserException_2_g$.ParserException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1477912:22)
    at new SpreadsheetParserException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1502415:24)
    at SpreadsheetColumnReferenceParser_1_g$.token0_1_g$ [as token0_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1499866:23)
    at SpreadsheetColumnReferenceParser_1_g$.token_17_g$ [as token_45_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1499853:37)
    at SpreadsheetColumnReferenceParser_1_g$.parseReference_0_g$ [as parseReference_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1499836:26)
    at SpreadsheetColumnReferenceParser_1_g$.parse_145_g$ [as parse_220_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1499820:24)
    at SpreadsheetColumnReferenceParser_1_g$.parse_146_g$ [as parse_216_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1499790:15)
    at AlternativesParser_1_g$.parse_162_g$ [as parse_216_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1522258:33)
    at ReportingParser_1_g$.reportIfNotEmpty_0_g$ [as reportIfNotEmpty_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1525506:35)
    at ParserReporterCondition$2_1_g$.parse_170_g$ [as parse_229_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1524518:22)
    at ReportingParser_1_g$.parse_171_g$ [as parse_216_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1525493:30)
    at AlternativesParser_1_g$.parse_162_g$ [as parse_216_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1522258:33)
    at parseTextOrFail_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1508463:36)
    at parseColumnOrRow_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1508377:42)
    at tryParse_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1425323:11)
    at parseList_3_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1425175:3)
    at parse_103_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1425610:22)
    at SpreadsheetRowSortSaveHistoryToken_1_g$.setSave0_34_g$ [as setSave0_36_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1437766:110)
    at HistoryToken$8methodref$setSave0$Type_1_g$.apply_33055_g$ [as apply_34361_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1432432:40)
    at SpreadsheetRowSortSaveHistoryToken_1_g$.setIfSpreadsheetIdHistoryToken_0_g$ [as setIfSpreadsheetIdHistoryToken_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1431895:42)
    at SpreadsheetRowSortSaveHistoryToken_1_g$.setSave_0_g$ [as setSave_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1432056:15)
    at SpreadsheetToolbarComponentItemAnchorViewportHighlight_1_g$.refresh_42_g$ [as refresh_51_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1461495:320)
    at SpreadsheetToolbarComponent_1_g$.refresh_30_g$ [as refresh_51_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1460278:15)
    at $componentLifecycleHistoryTokenQuery_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1440728:28)
    at SpreadsheetToolbarComponent_1_g$.componentLifecycleHistoryTokenQuery_10_g$ [as componentLifecycleHistoryTokenQuery_15_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1460185:3)
    at $onHistoryTokenChange_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1440758:20)
    at SpreadsheetToolbarComponent_1_g$.onHistoryTokenChange_26_g$ [as onHistoryTokenChange_33_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1460209:3)
    at HistoryTokenWatchersEvent_1_g$.accept_521_g$ [as accept_1144_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1432840:18)
    at lambda$0_317_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:1432728:12)
    at HistoryTokenWatchers$lambda$0$Type_1_g$.accept_518_g$ [as accept_1119_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1432774:3)
    at Watchers_1_g$.accept_1113_g$ [as accept_1119_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1566681:18)
    at HistoryTokenWatchers_1_g$.onHistoryTokenChange_3_g$ [as onHistoryTokenChange_33_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1432751:22)
    at App_1_g$.onHistoryTokenChange_0_g$ [as onHistoryTokenChange_32_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1428535:33)
    at App_1_g$.lambda$8_50_g$ [as lambda$8_71_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:1428348:8)
    at App$lambda$8$Type_1_g$.handleEvent_157_g$ [as handleEvent] (walkingkooka.spreadsheet.dominokit.App-0.js:1429020:25)
```

**Comment by mP1** [comment]
When HistoryToken is a row sort save followed by setHighlight returns this or the original row sort save. The `SpreadsheetToolbarComponentItemAnchorViewportHighlight` then attempts to call setSave with disable or enable which causes SpreadsheetColumnOrRowSpreadsheetComparatorsList.parse to fail when it tries to parse the first token holding "enable" or "disable" as a column or row.
