### ISSUE TITLE
Url with unknown spreadsheet-id breaks viewport rendering

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#611]
```
walkingkooka.spreadsheet.dominokit.App-0.js:sourcemap:648861 SpreadsheetViewportWidget.loadViewportCellsIfNecessary waiting for metadata
00:21:46.805 walkingkooka.spreadsheet.dominokit.App-0.js:sourcemap:648861 SpreadsheetMetadataFetcher.failure 404 Unable to load spreadsheet 2 java.lang.IllegalStateException: Unable to load spreadsheet 2
	at walkingkooka.spreadsheet.server.context.http.SpreadsheetContextHateosHandlerMetadataLoad.handleOne(SpreadsheetContextHateosHandlerMetadataLoad.java:56)
	at walkingkooka.spreadsheet.server.context.http.SpreadsheetContextHateosHandlerMetadataLoad.handleOne(SpreadsheetContextHateosHandlerMetadataLoad.java:32)
	at walkingkooka.net.http.server.hateos.HateosResourceSelectionOne.dispatch(HateosResourceSelectionOne.java:42)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.locateHandlerParseRequestBodyDispatchSetResponseStatusCode(HateosResourceMappingRouterBiConsumerRequest.java:244)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.methodSupportedTest(HateosResourceMappingRouterBiConsumerRequest.java:201)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.extractLinkRelation(HateosResourceMappingRouterBiConsumerRequest.java:163)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.parseSelectionOrBadRequest(HateosResourceMappingRouterBiConsumerRequest.java:147)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.handleResourceNameOrNotFound(HateosResourceMappingRouterBiConsumerRequest.java:123)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.extractResourceNameOrBadRequest(HateosResourceMappingRouterBiConsumerRequest.java:112)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumerRequest.dispatch(HateosResourceMappingRouterBiConsumerRequest.java:95)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumer.accept(HateosResourceMappingRouterBiConsumer.java:70)
	at walkingkooka.net.http.server.hateos.HateosResourceMappingRouterBiConsumer.accept(HateosResourceMappingRouterBiConsumer.java:32)
	at walkingkooka.spreadsheet.server.SpreadsheetHttpServerApiSpreadsheetBiConsumer.accept(SpreadsheetHttpServerApiSpreadsheetBiConsumer.java:152)
	at walkingkooka.spreadsheet.server.SpreadsheetHttpServerApiSpreadsheetBiConsumer.accept(SpreadsheetHttpServerApiSpreadsheetBiConsumer.java:62)
	at walkingkooka.spreadsheet.server.SpreadsheetHttpServer.handler(SpreadsheetHttpServer.java:193)
	at walkingkooka.net.http.server.HeadersCopyHttpRequestHttpResponseBiConsumer.accept(HeadersCopyHttpRequestHttpResponseBiConsumer.java:55)
	at walkingkooka.net.http.server.HeadersCopyHttpRequestHttpResponseBiConsumer.accept(HeadersCopyHttpRequestHttpResponseBiConsumer.java:30)
	at walkingkooka.net.http.server.StacktraceDumpingHttpRequestHttpResponseBiConsumer.accept(StacktraceDumpingHttpRequestHttpResponseBiConsumer.java:51)
	at walkingkooka.net.http.server.StacktraceDumpingHttpRequestHttpResponseBiConsumer.accept(StacktraceDumpingHttpRequestHttpResponseBiConsumer.java:30)
	at walkingkooka.net.http.server.jetty.JettyHttpServerHandler.handle(JettyHttpServerHandler.java:68)
	at walkingkooka.net.http.server.jetty.JettyHttpServerHandler.handle(JettyHttpServerHandler.java:59)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:516)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.j
```

**Comment by mP1** [comment]
Closed by #798
