### ISSUE TITLE
SpreadsheetPatternEditorComponent kind=NumberParse fails to parse "General".

### ISSUE THREAD

**Issue by mP1** [mP1/walkingkooka-spreadsheet-dominokit#826]

**Comment by mP1** [comment]
```
walkingkooka.spreadsheet.dominokit.App-0.js:812178 HistoryTokenWatchersEvent.accept exception: Invalid character 'G' at 0 in "General" InvalidCharacterException_1_g$ {stackTrace_1_g$: null, writableStackTrace_1_g$: true, backingJsObject_2_g$: Error: walkingkooka.InvalidCharacterException
    at InvalidCharacterException_1_g$.createError_0_g…, text_75_g$: 'General', position_22_g$: 0, …}appendToMessage_2_g$: ""backingJsObject_2_g$: Error: walkingkooka.InvalidCharacterException
    at InvalidCharacterException_1_g$.createError_0_g$ [as createError_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3442:10)
    at InvalidCharacterException_1_g$.initializeBackingError_0_g$ [as initializeBackingError_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:3505:48)
    at InvalidCharacterException_1_g$.Throwable_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3330:8)
    at InvalidCharacterException_1_g$.Exception_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3605:18)
    at InvalidCharacterException_1_g$.RuntimeException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:3652:18)
    at InvalidCharacterException_1_g$.IllegalArgumentException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:12484:25)
    at InvalidCharacterException_1_g$.InvalidTextException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:764483:33)
    at InvalidCharacterException_1_g$.InvalidCharacterException_2_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:764513:29)
    at new InvalidCharacterException_1_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:764508:34)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.failInvalid_0_g$ [as failInvalid_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:836139:19)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.visit_476_g$ [as visit_897_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:836466:8)
    at SpreadsheetFormatGeneralSymbolParserToken_1_g$.accept_514_g$ [as accept_1043_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:827488:16)
    at SpreadsheetFormatGeneralSymbolParserToken_1_g$.accept_488_g$ [as accept_1026_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:825253:12)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.accept_370_g$ [as accept_1027_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:773475:16)
    at SpreadsheetFormatGeneralParserToken_1_g$.acceptValues_1_g$ [as acceptValues_14_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:825996:18)
    at SpreadsheetFormatGeneralParserToken_1_g$.accept_513_g$ [as accept_1044_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:827419:10)
    at _.accept_1043_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:827425:8)
    at SpreadsheetFormatGeneralParserToken_1_g$.accept_488_g$ [as accept_1026_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:825253:12)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.accept_370_g$ [as accept_1027_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:773475:16)
    at SequenceParserToken_1_g$.acceptValues_3_g$ [as acceptValues_16_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:869761:18)
    at SequenceParserToken_1_g$.accept_749_g$ [as accept_1026_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:870337:10)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.accept_370_g$ [as accept_1027_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:773475:16)
    at SpreadsheetNumberParsePatternSpreadsheetFormatParserTokenVisitor_1_g$.startAccept_0_g$ [as startAccept_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:836146:8)
    at patterns_8_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:840534:16)
    at with_495_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:838881:61)
    at parseNumberParsePattern_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:835750:10)
    at SpreadsheetPatternKind$15methodref$parseNumberParsePattern$Type_1_g$.apply_32657_g$ [as apply_33325_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:841426:10)
    at SpreadsheetPatternKind_1_g$.parse_120_g$ [as parse_188_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:841214:39)
    at SpreadsheetCellPatternSelectHistoryToken_1_g$.setSave0_7_g$ [as setSave0_23_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:810186:197)
    at HistoryToken$4methodref$setSave0$Type_1_g$.apply_32239_g$ [as apply_33326_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:808801:40)
    at SpreadsheetCellPatternSelectHistoryToken_1_g$.setIfSpreadsheetNameHistoryToken0_0_g$ [as setIfSpreadsheetNameHistoryToken0_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:808568:42)
    at SpreadsheetCellPatternSelectHistoryToken_1_g$.setSave_0_g$ [as setSave_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:808639:15)
    at SpreadsheetPatternEditorComponent_1_g$.patternAnchor_2_g$ [as patternAnchor_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813543:160)
    at SpreadsheetPatternEditorComponent_1_g$.lambda$3_135_g$ [as lambda$3_136_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813255:15)
    at SpreadsheetPatternEditorComponent$lambda$3$Type_1_g$.apply_33418_g$ [as apply_33325_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813938:32)
    at lambda$6_79_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:813196:46)
    at SpreadsheetPatternEditorComponent$lambda$6$Type_1_g$.asElement_8_g$ [as asElement_4_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:814013:10)
    at RowCell_1_g$.updateCell_0_g$ [as updateCell_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:78940:88)
    at TableRow_1_g$.renderCell_0_g$ [as renderCell_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:80137:16)
    at TableRow$DefaultRowRenderer$0methodref$renderCell$Type_1_g$.accept_180_g$ [as accept_1014_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:80356:25)
    at ArrayList_1_g$.forEach_9_g$ [as forEach_51_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:44547:19)
    at TableRow$DefaultRowRenderer_1_g$.render_1_g$ [as render_4_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:80337:58)
    at TableRow_1_g$.render_0_g$ [as render_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:80128:27)
    at TableConfig_1_g$.drawRecord_0_g$ [as drawRecord_1_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:79166:17)
    at DataTable_1_g$.addRows_1_g$ [as addRows_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:75508:27)
    at DataTable_1_g$.setData_4_g$ [as setData_9_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:75810:10)
    at DataTable_1_g$.lambda$3_22_g$ [as lambda$3_102_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:75414:12)
    at DataTable$lambda$3$Type_1_g$.onDataChanged_0_g$ [as onDataChanged_2_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:76100:25)
    at LocalListDataStore_1_g$.lambda$3_26_g$ [as lambda$3_104_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:81354:29)
    at LocalListDataStore$lambda$3$Type_1_g$.accept_194_g$ [as accept_1014_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:81795:25)
    at ArrayList_1_g$.forEach_9_g$ [as forEach_51_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:44547:19)
    at LocalListDataStore_1_g$.fireUpdate_1_g$ [as fireUpdate_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:81388:25)
    at LocalListDataStore_1_g$.load_4_g$ [as load_6_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:81506:8)
    at LocalListDataStore_1_g$.setData_5_g$ [as setData_10_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:81594:8)
    at SpreadsheetPatternEditorComponent_1_g$.sampleDataPrepare_2_g$ [as sampleDataPrepare_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813632:38)
    at SpreadsheetPatternEditorComponent_1_g$.onPatternTextBox_2_g$ [as onPatternTextBox_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813494:8)
    at SpreadsheetPatternEditorComponent_1_g$.setPatternText_2_g$ [as setPatternText_3_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813649:8)
    at SpreadsheetPatternEditorComponent_1_g$.refresh_6_g$ [as refresh_8_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813618:8)
    at $onHistoryTokenChange_0_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:807391:24)
    at SpreadsheetPatternEditorComponent_1_g$.onHistoryTokenChange_16_g$ [as onHistoryTokenChange_11_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:813277:3)
    at HistoryTokenWatchersEvent_1_g$.accept_434_g$ [as accept_1039_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:809249:18)
    at lambda$0_255_g$ (walkingkooka.spreadsheet.dominokit.App-0.js:809160:12)
    at HistoryTokenWatchers$lambda$0$Type_1_g$.accept_431_g$ [as accept_1014_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:809206:3)
    at Watchers_1_g$.accept_1008_g$ [as accept_1014_g$] (walkingkooka.spreadsheet.dominokit.App-0.js:911361:18)position_22_g$: 0stackTrace_1_g$: nulltext_75_g$: "General"writableStackTrace_1_g$: true[[Prototype]]: Object
```
